Repository PlanIT-3/PLANIT_BE, pull requests merged in 2025-08, with the labels that each got.

#31 [Bug #30]: 컨트롤러 응답값 ResponseEntity로 감싸기
  src/main/java/woojooin/planit/domain/object/isa/controller/IsaAccountController.java
Labels: bug

#33 [BUG #32]: ISA 계좌 유저 상품 관련 api 변경
  src/main/java/woojooin/planit/domain/object/isa/controller/IsaAccountController.java
Labels: bug

#42 [Bug: #41] 백엔드 api 수정
  src/main/java/woojooin/planit/domain/goal/service/GoalSettingService.java
  src/main/java/woojooin/planit/domain/object/isa/controller/IsaAccountController.java
  src/main/java/woojooin/planit/domain/object/isa/dto/req/IsaAccountProductEditReq.java
  src/main/java/woojooin/planit/domain/object/isa/dto/req/IsaAccountProductRegisterReq.java
  src/main/java/woojooin/planit/domain/object/isa/dto/res/IsaAccountProductRes.java
  src/main/java/woojooin/planit/domain/object/isa/mapper/IsaAccountMapper.java
  src/main/java/woojooin/planit/domain/object/isa/service/IsaAccountService.java
  src/main/resources/mapper/IsaAccountMapper.xml
Labels: bug

#50 [feat#48] - 목표 진행 추이 api 개발
  src/main/java/woojooin/planit/domain/account/domain/Account.java
  src/main/java/woojooin/planit/domain/goal/controller/GoalController.java
  src/main/java/woojooin/planit/domain/goal/domain/GoalProgress.java
  src/main/java/woojooin/planit/domain/goal/dto/GoalProgressGraphDTO.java
  src/main/java/woojooin/planit/domain/goal/mapper/GoalMapper.java
  src/main/java/woojooin/planit/domain/goal/service/GoalSettingService.java
  src/main/resources/mapper/goal/GoalMapper.xml
Labels: feat

#52 [Feature #51]: 일/주/월 별 잔고 조회
  src/main/java/woojooin/planit/domain/account/controller/AccountController.java
  src/main/java/woojooin/planit/domain/account/domain/BalanceData.java
  src/main/java/woojooin/planit/domain/account/domain/DailyBalance.java
  src/main/java/woojooin/planit/domain/account/dto/res/BalanceListRes.java
  src/main/java/woojooin/planit/domain/account/dto/res/BalanceRes.java
  src/main/java/woojooin/planit/domain/account/mapper/AccountMapper.java
  src/main/java/woojooin/planit/domain/account/service/AccountService.java
  src/main/java/woojooin/planit/domain/goal/mapper/GoalMapper.java
  src/main/java/woojooin/planit/global/config/RootConfig.java
  src/main/resources/mapper/AccountMapper.xml
Labels: feat

#61 [BUG #60]: cors 해결
  src/main/java/woojooin/planit/global/config/ServletConfig.java
Labels: bug

#65 [REFACTOR #64]: 일/주/월 재산 데이터 응답 속도 개선
  src/main/java/woojooin/planit/domain/account/mapper/AccountMapper.java
  src/main/java/woojooin/planit/domain/account/service/AccountService.java
  src/main/java/woojooin/planit/global/config/ServletConfig.java
  src/main/java/woojooin/planit/global/security/SecurityConfig.java
  src/main/resources/mapper/AccountMapper.xml
Labels: refactor
